# === Application ===
spring.application.name=businessai-backend
server.port=8080

# === MongoDB ===
spring.data.mongodb.uri=mongodb://localhost:27017/businessai_db
spring.data.mongodb.database=businessai_db

jwt.secret=ThisIsAVeryLongSecretKeyForJWTThatMustBeAtLeast32Characters
jwt.expiration=86400000
# === Logs ===
logging.level.org.springframework.data.mongodb=DEBUG

# === JSON dates ===
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC